[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = false
lto = "fat"
codegen-units = 1
opt-level = 3
incremental = false
panic = "abort"
strip = "symbols"
debug = false

[profile.release.package."*"]
opt-level = 3
codegen-units = 1